name: 'Konflux Banner YAML Validator'
description: 'Validate banner YAML files in clusters folder with JSON Schema'

inputs:
  folder:
    description: 'Folder containing banner YAML files'
    required: true
    default: './clusters'
  schema_path:
    description: 'Path to JSON schema file'
    required: true
    default: '.github/schema/banner-schema.json'

runs:
  using: "composite"
  steps:
  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: 16

  - name: Install ajv-cli, yamljs
    run: |
      npm install -g ajv-cli yamljs
    shell: bash

  - name: Validate YAML files against schema
    shell: bash
    run: |
      files=$(find ${{ inputs.folder }} -type f \( -name "*.yaml" \))
      error=0
      schema_path="${GITHUB_WORKSPACE}/${{ inputs.schema_path }}"
      for f in $files; do
        echo -n "Validating $f ... "
        YAML_JSON=$(yaml2json "$f")
        tmp_data_file=$(mktemp /tmp/tmpfile.XXXXXX.json)
        echo "$YAML_JSON" > "$tmp_data_file"

        if ajv validate -s "$schema_path" -d "$tmp_data_file" --strict=true >/dev/null 2>&1; then
          echo "valid"
        else
          echo "FAILED"
          error=1
        fi

        rm "$tmp_data_file"
      done

      if [ $error -eq 1 ]; then
        echo "YAML validation failed."
        exit 1
      fi
