apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: konflux-banner

configMapGenerator:
  - name: konflux-banner-configmap
    files:
      - banner-content.yaml

generatorOptions:
  disableNameSuffixHash: true

