name: Validate Banner YAML

on:
  push:
    paths:
    - 'clusters/**/*.yaml'
  pull_request:
    paths:
    - 'clusters/**/*.yaml'

permissions: read-all

jobs:
  validate-banner:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run banner validation via Makefile
      run: make all
