name: Validate Banner YAML

on:
  push:
    paths:
    - 'clusters/**/*.yaml'
  pull_request:
    paths:
    - 'clusters/**/*.yaml'

permissions: read-all

jobs:
  validate-banner:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Enforce .yaml file extension
      run: |
        invalid_files=$(find ./clusters -type f -name "*.yml")
        if [ -n "$invalid_files" ]; then
          echo "❌ Found files using .yml extension:"
          echo "$invalid_files"
          echo "Please rename them to .yaml"
          exit 1
        else
          echo "✅ No .yml files found."
        fi

    - name: Validate banner YAML files
      uses: ./.github/actions/konflux-banner-validator
      with:
        folder: './clusters'

    - name: Validate Content Security
      uses: ./.github/actions/konflux-banner-security
      with:
        folder: './clusters'
